/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio.Forms;

import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import negocio.Controladoras.ControladoraProductos;
import negocio.Controladoras.InvalidParameterException;
import negocio.Controladoras.StorageException;
import negocio.Entidades.Productos;

/**
 *
 * @author usuario
 */
public class ABMProductos extends javax.swing.JDialog {

    Frame formParent = null;
    static Productos productoModificar = null;
    /**
     * Creates new form ABMProductos
     */
    public ABMProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
        //Tener al Frame padre guardado para usar.
        formParent = parent;
        //Seteo de los valores de las filas de la tabla en el centro
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i=0; i<form_tablaProductos.getColumnCount();i++){
            form_tablaProductos.setDefaultRenderer(form_tablaProductos.getColumnClass(i),renderer);
        }
        //Seteo de los valores de las cabezeras de la tabla en el centro
        DefaultTableCellRenderer renderer2 = (DefaultTableCellRenderer) form_tablaProductos.getTableHeader().getDefaultRenderer();
        renderer2.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        form_eliminarProducto = new javax.swing.JButton();
        form_agregarProducto = new javax.swing.JButton();
        form_modificarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alta - Baja - Modificacion de Productos");

        form_eliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        form_eliminarProducto.setText("Eliminar producto");
        form_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_eliminarProductoActionPerformed(evt);
            }
        });

        form_agregarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        form_agregarProducto.setText("Agregar producto");
        form_agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_agregarProductoActionPerformed(evt);
            }
        });

        form_modificarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        form_modificarProducto.setText("Modificar producto");
        form_modificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_modificarProductoActionPerformed(evt);
            }
        });

        form_tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Producto", "Stock", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        form_tablaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(form_tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(form_agregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_modificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_eliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {form_agregarProducto, form_eliminarProducto, form_modificarProducto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_modificarProducto)
                    .addComponent(form_eliminarProducto)
                    .addComponent(form_agregarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de agregar producto
    private void form_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_agregarProductoActionPerformed
        AltaProducto altaProducto = new AltaProducto(formParent, rootPaneCheckingEnabled);
        altaProducto.setVisible(true);
    }//GEN-LAST:event_form_agregarProductoActionPerformed

    //Evento en el que la ventana ABMProductos gana el foco del programa.
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        refreshDataTable();
    }//GEN-LAST:event_formWindowGainedFocus

    //Boton para eliminar el producto seleccionado
    private void form_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_eliminarProductoActionPerformed
        Productos p = obtenerProveedorSeleccionado(form_tablaProductos);
        if(p != null){
            try {
                ControladoraProductos.eliminarProducto(p);
                JOptionPane.showMessageDialog(null,"El producto ha sido eliminado correctamente.","Eliminar producto",JOptionPane.PLAIN_MESSAGE);
            } catch (InvalidParameterException | StorageException ex) {
                Logger.getLogger(ABMProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Debes seleccionar el producto a eliminar.","Alerta error",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_form_eliminarProductoActionPerformed

    //Boton para modificar el producto seleccionado.
    private void form_modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_modificarProductoActionPerformed
        productoModificar = obtenerProveedorSeleccionado(form_tablaProductos);
        if(productoModificar != null){
            ModificarProducto modificar = new ModificarProducto(formParent, rootPaneCheckingEnabled);
            modificar.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null,"Debes seleccionar el producto a modificar.","Alerta error",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_form_modificarProductoActionPerformed

    //Funcion para obtener el producto seleccionado de la tabla.
    public Productos obtenerProveedorSeleccionado(JTable tabla){
        Productos p = null;
        if(form_tablaProductos.getSelectedRow() != -1){
            try {
                List<Productos> prod = null;
                int filaElegida = form_tablaProductos.getSelectedRow();
                prod = ControladoraProductos.getProductos();
                p = prod.get(filaElegida);
            } catch (StorageException ex) {
                Logger.getLogger(ABMProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return p;
    }
    
    //Funcion para actualizar los valores mostrados en la tabla.
    public void refreshDataTable(){
        DefaultTableModel modelo = (DefaultTableModel) form_tablaProductos.getModel();        
        //Borrar los valores que ya existen, para no repetirlos en la tabla.
        if (modelo.getRowCount() > 0) {
            for (int i = modelo.getRowCount() - 1; i > -1; i--) {
                modelo.removeRow(i);
            }
        }
        //Volver a imprimir todos los datos en la tabla.
        List<Productos> prod = null;
        try {
            prod = ControladoraProductos.getProductos();
            for(Productos p : prod){
                String[] data = new String[4];
                data[0] = p.getIdProducto().toString();
                data[1] = p.getProducto();
                data[2] = String.valueOf(p.getStock());
                data[3] = String.valueOf(p.getPrecio());
                modelo.addRow(data);
            }
            form_tablaProductos.setModel(modelo);
        } catch (StorageException ex) {
            Logger.getLogger(ABMProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMProductos dialog = new ABMProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_agregarProducto;
    private javax.swing.JButton form_eliminarProducto;
    private javax.swing.JButton form_modificarProducto;
    private javax.swing.JTable form_tablaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
