/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio.Forms;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import negocio.Controladoras.ControladoraAltaCompra;
import negocio.Controladoras.ControladoraCompras;
import negocio.Controladoras.ControladoraDetalles;
import negocio.Controladoras.ControladoraMedia;
import negocio.Controladoras.ControladoraProductos;
import negocio.Controladoras.InvalidParameterException;
import negocio.Controladoras.StorageException;
import negocio.Entidades.Compras;
import negocio.Entidades.Detalles;
import negocio.Entidades.DetallesId;
import negocio.Entidades.Proveedores;
import negocio.Entidades.Productos;

/**
 *
 * @author usuario
 */
public class AltaCompra extends javax.swing.JDialog {

    float total = 0;
    /**
     * Creates new form AltaCompra
     */
    public AltaCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Seteo de los valores de las filas de la tabla en el centro
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i=0; i<form_tablaProductos.getColumnCount();i++){
            form_tablaProductos.setDefaultRenderer(form_tablaProductos.getColumnClass(i),renderer);
        }
        //Seteo de los valores de las cabezeras de la tabla en el centro
        DefaultTableCellRenderer renderer2 = (DefaultTableCellRenderer) form_tablaProductos.getTableHeader().getDefaultRenderer();
        renderer2.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        form_fecha = new javax.swing.JFormattedTextField();
        form_precio = new javax.swing.JTextField();
        form_cantidad = new javax.swing.JTextField();
        form_botonRealizarCompra = new javax.swing.JButton();
        form_comboProveedor = new javax.swing.JComboBox();
        form_comboProducto = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_tablaProductos = new javax.swing.JTable();
        form_botonAgregarProducto = new javax.swing.JButton();
        form_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Realizar una nueva compra");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Producto:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Proveedor:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de compra:");

        form_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        form_fecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        form_fecha.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_precio.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_cantidad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_botonRealizarCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_botonRealizarCompra.setText("Realizar compra");
        form_botonRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_botonRealizarCompraActionPerformed(evt);
            }
        });

        form_comboProveedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_comboProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Proveedor", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(form_tablaProductos);

        form_botonAgregarProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_botonAgregarProducto.setText("Agregar productos a la compra");
        form_botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_botonAgregarProductoActionPerformed(evt);
            }
        });

        form_total.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_total.setText("Costo total de la compra: $0.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(form_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(form_comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(form_comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(form_botonAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(form_botonRealizarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(form_total)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(form_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(form_botonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_botonRealizarCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento en el que gana el foco el form para completar los combos y la fecha actual.
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(form_comboProducto.getItemCount() <= 0 && form_comboProveedor.getItemCount() <= 0){
            //Completar los combos con los productos y los proveedores.
            try{
                ControladoraAltaCompra.completarComboBoxDeProductosYProveedores(form_comboProducto, form_comboProveedor);
            } catch (StorageException ex) {
                Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Se produjo un error al intentar cargar los productos y/o los proveedores.","Error!",JOptionPane.PLAIN_MESSAGE);
            }
        }
        //Completar la fecha con la fecha actual.
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        form_fecha.setText(dateFormat.format(date));
    }//GEN-LAST:event_formWindowGainedFocus
    
    //Boton para realizar la compra y guardarla en la BD
    private void form_botonRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_botonRealizarCompraActionPerformed
        //TODO: CODE HERE
        DefaultTableModel modelo = (DefaultTableModel) form_tablaProductos.getModel();
        //Generar el producto necesario para el detalle, a partir del producto seleccionado.
        Productos productoAgregar = null;
        List<Productos> listaProd;
        try {
            listaProd = ControladoraProductos.getProductos();
            for(Productos p : listaProd){
                if(p.getProducto().equals(form_comboProducto.getSelectedItem().toString()))
                    productoAgregar = p;
            }
        } catch (StorageException ex) {
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Generar la compra necesario para el detalle, a partir de la fecha seleccionada.
        Date date = null;
        try {
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            date = formatter.parse(form_fecha.getText());
        } catch (ParseException ex) {
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //ACA HAY QUE SEGUIR
        //ACA HAY QUE SEGUIR
        //ACA HAY QUE SEGUIR
        //ACA HAY QUE SEGUIR
        //ACA HAY QUE SEGUIR
        try {
            ControladoraCompras.agregarCompra(date, null);
        } catch (InvalidParameterException | StorageException ex) {
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        List<Compras> c = null;
        try {
            c = ControladoraCompras.getCompras();
        } catch (StorageException ex) {
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ultimoIndex = c.lastIndexOf(c),
            idCompra = c.get(ultimoIndex).getIdCompra();
        
        Set<Detalles> setDetalles = new HashSet<>();
        Detalles detail = new Detalles();
        DetallesId dID = new DetallesId(productoAgregar.getIdProducto(),idCompra);
        
        
        for(int j = 0; j<modelo.getRowCount();j++){
            for(int i = 0; i<modelo.getColumnCount(); i++){
                Integer cant = Integer.valueOf(form_cantidad.getText());
                Float totalProd = Float.valueOf(form_precio.getText());
                listaDetalles.add(new Detalles(null, null, productoAgregar, totalProd, cant));
            }
        }
        
        //Detalles details = new Detalles(detailID, compras, productos, total, cantidad);
        //Compras compra = new Compras(fecha, detalles);
    }//GEN-LAST:event_form_botonRealizarCompraActionPerformed

    //Boton de agregar productos a la tabla de compras.
    private void form_botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_botonAgregarProductoActionPerformed
        //Checkeo de todas las variables a ingresar a la compra.
        boolean error = ControladoraAltaCompra.validarDatosAltaCompra(form_comboProducto, form_comboProveedor, form_cantidad, form_precio);
        if (!error){
            //Agregar los valores a la tabla.
            DefaultTableModel modelo = (DefaultTableModel) form_tablaProductos.getModel();
            total += Float.valueOf(form_precio.getText()) * Integer.valueOf(form_cantidad.getText());
            String[] data = new String[5];
            data[0] = form_comboProducto.getSelectedItem().toString();
            data[1] = form_comboProveedor.getSelectedItem().toString();
            data[2] = form_cantidad.getText();
            data[3] = form_precio.getText();
            float totalProd = Float.valueOf(form_precio.getText()) * Integer.valueOf(form_cantidad.getText());
            data[4] = String.valueOf(totalProd);
            modelo.addRow(data);
            form_tablaProductos.setModel(modelo);
            form_total.setText("Costo total de la compra: $" + String.valueOf(total) + ".");
        }
    }//GEN-LAST:event_form_botonAgregarProductoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaCompra dialog = new AltaCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_botonAgregarProducto;
    private javax.swing.JButton form_botonRealizarCompra;
    private javax.swing.JTextField form_cantidad;
    private javax.swing.JComboBox form_comboProducto;
    private javax.swing.JComboBox form_comboProveedor;
    private javax.swing.JFormattedTextField form_fecha;
    private javax.swing.JTextField form_precio;
    private javax.swing.JTable form_tablaProductos;
    private javax.swing.JLabel form_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
