/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio.Forms;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import negocio.Controladoras.ControladoraProductos;
import negocio.Controladoras.ControladoraProveedores;
import negocio.Controladoras.InvalidParameterException;
import negocio.Controladoras.StorageException;
import negocio.Entidades.Proveedores;

/**
 *
 * @author usuario
 */
public class AltaProducto extends javax.swing.JDialog {

    /**
     * Creates new form AltaProducto
     */
    public AltaProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
        //Rellenar los valores del componente de los proveedores.
        rellenarComboBox(form_proveedor);
    }

    private void rellenarComboBox(JComboBox combo){
        List<Proveedores> prov = null;
        try {
            prov = ControladoraProveedores.getProveedores();
            for(Proveedores p : prov)
                combo.addItem(p.getProveedor());
        } catch (StorageException ex) {
            Logger.getLogger(AltaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        form_producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        form_stock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        form_proveedor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        form_agregarProducto = new javax.swing.JButton();
        form_precio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Alta de producto");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Producto:");

        form_producto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        form_producto.setToolTipText("<html>\n\t<strong>El nombre del producto.</strong>\n</html>");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Stock:");

        form_stock.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        form_stock.setToolTipText("<html>\n\t<strong>El stock del producto a agregar.</strong>\n\t<strong><br>La cantidad se ingresa de forma entera, es decir: en lugar de ingresar 2KG se debe ingresar \t\t2000</strong>\n</html>");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Precio:");

        form_proveedor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        form_proveedor.setToolTipText("<html>\n\t<strong>El proveedor que tiene el producto.</strong>\n</html>");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Proveedor:");

        form_agregarProducto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        form_agregarProducto.setText("Agregar producto");
        form_agregarProducto.setToolTipText("<html>\n\t<strong>Realizar el alta del producto.</strong>\n</html>");
        form_agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_agregarProductoActionPerformed(evt);
            }
        });

        form_precio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        form_precio.setToolTipText("<html>\n\t<strong>El precio del producto.\n\t<br>El precio debe ser del siguiente formato: 000.00</strong>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(form_agregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(form_proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(form_stock)
                            .addComponent(form_producto)
                            .addComponent(form_precio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(form_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_agregarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_agregarProductoActionPerformed
        //Obtener los datos asignados en el form.
        String producto = form_producto.getText();
        int stock = Integer.valueOf(form_stock.getText());
        float precio = Float.valueOf(form_precio.getText());
        Proveedores p = obtenerProveedorSeleccionado(form_proveedor);
        boolean error = true;
        //Realizar el alta del producto en la BD
        try {
            ControladoraProductos.agregarProducto(p, producto, stock, precio);
            error = false;
        } catch (InvalidParameterException | StorageException ex) {
            Logger.getLogger(AltaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Checkear si se quiere seguir agregando mas productos.
        if (!error && JOptionPane.showConfirmDialog(null, "El producto ha sido agregado correctamente. \nDesea seguir agregando productos?", "Agregar más productos", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            //Vaciar los strings con los datos del producto.
            form_precio.setText(""); form_producto.setText(""); form_stock.setText(""); form_proveedor.setSelectedIndex(-1);
        }
        else
            this.setVisible(false);
    }//GEN-LAST:event_form_agregarProductoActionPerformed

    //Funcion para obtener el proveedor seleccionado de la tabla.
    public Proveedores obtenerProveedorSeleccionado(JComboBox combo){
        Proveedores p = null;
        List<Proveedores> prov = null;
        String provElegido = (String) combo.getSelectedItem();
        if(combo.getSelectedItem() != null){
            try {
                prov = ControladoraProveedores.getProveedores();
                for(Proveedores pr : prov){
                    if(pr.getProveedor().equals(provElegido))
                        p = pr;
                }
            } catch (StorageException ex) {
                Logger.getLogger(VistaProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return p;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaProducto dialog = new AltaProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_agregarProducto;
    private javax.swing.JTextField form_precio;
    private javax.swing.JTextField form_producto;
    private javax.swing.JComboBox form_proveedor;
    private javax.swing.JTextField form_stock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
