/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio.Forms;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import negocio.Controladoras.ControladoraAltaCompra;
import negocio.Controladoras.ControladoraCompras;
import negocio.Controladoras.ControladoraDetalles;
import negocio.Controladoras.ControladoraProductos;
import negocio.Controladoras.ControladoraProveedores;
import negocio.Controladoras.InvalidParameterException;
import negocio.Controladoras.StorageException;
import negocio.Entidades.Compras;
import negocio.Entidades.Detalles;
import negocio.Entidades.Productos;
import negocio.Entidades.Proveedores;
import negocio.Hibernate.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author usuario
 */
public class AltaCompra extends javax.swing.JDialog {

    float total = 0;
    List<Detalles> listaDetalles;
    boolean error = false;
    /**
     * Creates new form AltaCompra
     */
    public AltaCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Inicializar la lista de detalles.
        listaDetalles = new ArrayList();
        //Seteo de los valores de las filas de la tabla en el centro
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i=0; i<form_tablaProductos.getColumnCount();i++){
            form_tablaProductos.setDefaultRenderer(form_tablaProductos.getColumnClass(i),renderer);
        }
        //Seteo de los valores de las cabezeras de la tabla en el centro
        DefaultTableCellRenderer renderer2 = (DefaultTableCellRenderer) form_tablaProductos.getTableHeader().getDefaultRenderer();
        renderer2.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        form_fecha = new javax.swing.JFormattedTextField();
        form_precio = new javax.swing.JTextField();
        form_cantidad = new javax.swing.JTextField();
        form_botonRealizarCompra = new javax.swing.JButton();
        form_comboProveedor = new javax.swing.JComboBox();
        form_comboProducto = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_tablaProductos = new javax.swing.JTable();
        form_botonAgregarProducto = new javax.swing.JButton();
        form_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Realizar una nueva compra");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Producto:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Proveedor:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de compra:");

        form_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        form_fecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        form_fecha.setToolTipText("<html>\n\t<strong>La fecha de la compra.</strong>\n</html>");
        form_fecha.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_precio.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_precio.setToolTipText("<html>\n\t<strong>El precio del producto comprado.\n\t<br> El precio es el de lista, en caso de que sea otro, modificarlo.</strong>\n</html>");

        form_cantidad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_cantidad.setToolTipText("<html>\n\t<strong>La cantidad del producto comprada.</strong>\n</html>");

        form_botonRealizarCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_botonRealizarCompra.setText("Realizar compra");
        form_botonRealizarCompra.setToolTipText("<html>\n\t<strong>Realizar la compra con los productos agregados.</strong>\n</html>");
        form_botonRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_botonRealizarCompraActionPerformed(evt);
            }
        });

        form_comboProveedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_comboProveedor.setToolTipText("<html>\n\t<strong>El proveedor al que se le compro.</strong>\n</html>");
        form_comboProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                form_comboProveedorItemStateChanged(evt);
            }
        });

        form_comboProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_comboProducto.setToolTipText("<html>\n\t<strong>El producto que se compro.</strong>\n</html>");

        form_tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Proveedor", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(form_tablaProductos);

        form_botonAgregarProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_botonAgregarProducto.setText("Agregar producto a la compra");
        form_botonAgregarProducto.setToolTipText("<html>\n\t<strong>Agregar el producto a la compra.</strong>\n</html>");
        form_botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_botonAgregarProductoActionPerformed(evt);
            }
        });

        form_total.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_total.setText("Costo total de la compra: $0.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_botonRealizarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(form_total))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(20, 20, 20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(form_cantidad)
                                        .addComponent(form_comboProveedor, 0, 277, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(form_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(form_comboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(form_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(form_botonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(form_comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(form_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_botonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_botonRealizarCompra)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento en el que gana el foco el form para completar los combos y la fecha actual.
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        //Completar los combos con los productos y los proveedores.
        if(form_comboProducto.getItemCount() <= 0 && form_comboProveedor.getItemCount() <= 0){
            ControladoraAltaCompra.completarComboBoxDeProductosYProveedores(form_comboProducto, form_comboProveedor);
        }
        //Completar la fecha con la fecha actual.
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        form_fecha.setText(dateFormat.format(date));
        //Eliminar de la tabla los valores de la compra que ya se ha realizado.
        if(!error){
            DefaultTableModel renderer = (DefaultTableModel) form_tablaProductos.getModel();
            renderer.setRowCount(0);
        }
        //Deshabilitar la opcion de elegir un producto.
        form_comboProducto.setEnabled(false);
    }//GEN-LAST:event_formWindowGainedFocus
    
    
    //Boton para realizar la compra y guardarla en la BD
    private void form_botonRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_botonRealizarCompraActionPerformed
        error = false;
        //Verificar si la fecha ingresada es correcta, y guardarla para utilizar luego en la compra
        Date date = ControladoraAltaCompra.parsearFecha(form_fecha);
        //Agregar una nueva compra en la BD con la fecha ingresada, para obtener el ID necesario para los detalles.
        try {
            ControladoraCompras.agregarCompra(date, null);
        } catch (InvalidParameterException | StorageException ex) {
            JOptionPane.showMessageDialog(null,"Se produjo un error al intentar guardar la compra.","Error!",JOptionPane.WARNING_MESSAGE);
            error = true;
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Obtener la ultima compra, realizada anteriormente, para agregar en el detalle.
        Session session = HibernateUtil.getSessionFactory().openSession();
        Compras ultimaCompra = ControladoraAltaCompra.obtenerUltimaCompra(session);
        //updatear los detalles de la compra, para luego mostrar cuando necesario. - - Don't know if this is really needed.
        for(Detalles d : listaDetalles){
            d.setCompras(ultimaCompra);
            d.getProductos().setDetalleses(new HashSet<>(listaDetalles));
            ultimaCompra.getDetalleses().add(d);
        }
        session.close();
        
        //Updatear la compra con los detalles agregados.
        try {
            ControladoraCompras.updateCompra(ultimaCompra);
        } catch (StorageException ex) {
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
            error = true;
            JOptionPane.showMessageDialog(null,"Error al intentar updatear la compra con el set de detalles.","Error AltaCompra - form_botonRealizarCompraActionPerformed!",JOptionPane.PLAIN_MESSAGE);
        }
        
        //Updatear los stocks de los productos segun la cantidad comprada.
        for(Detalles d : listaDetalles){
            try {
                Productos p = ControladoraProductos.getProduct(d.getProductos().getIdProducto());
                int nuevoStock = p.getStock() + d.getCantidad();
                Proveedores pr = ControladoraProveedores.getProveedor(p.getIdProveedor());
                ControladoraProductos.updateProducto(p, p.getProducto(), nuevoStock, p.getPrecio(), pr);
            } catch (StorageException ex) {
                Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error al actualizar el stock de los productos.","Error AltaCompra - form_botonRealizarCompraActionPerformed!",JOptionPane.PLAIN_MESSAGE);
            }
        }
        
        //Finalmente, realizar la compra de los detalles correspondientes, agregando a la BD.
        if(ultimaCompra != null && !error){
            for(Detalles d : listaDetalles){
                d.setCompras(ultimaCompra);
                try {
                    ControladoraDetalles.agregarDetalle(d.getCompras(),d.getProductos(), (d.getTotal()* d.getCantidad()), d.getCantidad());
                } catch (InvalidParameterException | StorageException ex) {
                    Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
                    error = true;
                    JOptionPane.showMessageDialog(null,"Se produjo un error al intentar guardar los detalles de la compra.","Error!",JOptionPane.WARNING_MESSAGE);
                }
            }
            //Si no se produjo ningun error, mostrar el cartel de exito.
            if(!error){
                JOptionPane.showMessageDialog(null,"Compra realizada correctamente.","Completado!",JOptionPane.PLAIN_MESSAGE);
                //Resetear la lista de detalles, en caso de que la ventana se volviera a abrir para que no queden guardados los antiguos datos.
                listaDetalles = new ArrayList();
            }
        }
    }//GEN-LAST:event_form_botonRealizarCompraActionPerformed

    //Boton de agregar productos a la tabla de compras.
    private void form_botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_botonAgregarProductoActionPerformed
        //Checkeo de todas las variables a ingresar a la compra.
        boolean error = ControladoraAltaCompra.validarDatosAltaCompra(form_comboProducto, form_comboProveedor, form_cantidad, form_precio);
        //Verificar si la fecha ingresada es correcta, y guardarla para utilizar luego en la compra
        Date date = ControladoraAltaCompra.parsearFecha(form_fecha);
        if (!error && date != null){
            //Agregar los valores a la tabla.
            DefaultTableModel modelo = (DefaultTableModel) form_tablaProductos.getModel();
            total += Float.valueOf(form_precio.getText()) * Integer.valueOf(form_cantidad.getText());
            String[] data = new String[5];
            data[0] = form_comboProducto.getSelectedItem().toString();
            data[1] = form_comboProveedor.getSelectedItem().toString();
            data[2] = form_cantidad.getText();
            data[3] = form_precio.getText();
            float totalProd = Float.valueOf(form_precio.getText()) * Integer.valueOf(form_cantidad.getText());
            data[4] = String.valueOf(totalProd);
            modelo.addRow(data);
            form_tablaProductos.setModel(modelo);
            form_total.setText("Costo total de la compra: $" + String.valueOf(total) + ".");
            
            int debug = listaDetalles.size();
            //Agregar el detalle a la lista, para luego agregar en la BD
            agregarDetalleALista(form_comboProducto.getSelectedItem().toString(), form_precio.getText(), form_cantidad.getText());
        }
    }//GEN-LAST:event_form_botonAgregarProductoActionPerformed

    //Funcion para agregar los valores en la lista de detalles, que luego se guardara en la BD
    public void agregarDetalleALista(String nombreProducto, String precio, String cantidad){
        //Obtener el producto elegido para agregar al detalle.
        Productos prod = null;
        List<Productos> listaProducto;
        try {
            listaProducto = ControladoraProductos.getProductos();
            for(Productos p : listaProducto){
                if(p.getProducto().equals(nombreProducto))
                    prod = p;
            }
        } catch (StorageException ex) {
            JOptionPane.showMessageDialog(null,"Error al cargar el detalle.","Error!",JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(AltaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Obtener el precio y la cantidad comprada.
        float floatPrecio = Float.valueOf(precio);
        int intCantidad = Integer.valueOf(cantidad);
        //Agregar el detalle a la lista.
        Detalles detail = new Detalles(null,prod, floatPrecio,intCantidad);
        listaDetalles.add(detail);
    }
    
    //Evento que sucede al cambiar de item en el combo de proveedores para mostrar los productos de este elegido.
    private void form_comboProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_form_comboProveedorItemStateChanged
        ControladoraAltaCompra.completarComboProductosSegunProveedor(form_comboProducto, form_comboProveedor.getSelectedItem().toString(),form_precio);
        if(form_comboProducto.getSelectedItem().equals("Seleccionar..."))
            form_comboProducto.setEnabled(false);
        else
            form_comboProducto.setEnabled(true);
    }//GEN-LAST:event_form_comboProveedorItemStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaCompra dialog = new AltaCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_botonAgregarProducto;
    private javax.swing.JButton form_botonRealizarCompra;
    private javax.swing.JTextField form_cantidad;
    private javax.swing.JComboBox form_comboProducto;
    private javax.swing.JComboBox form_comboProveedor;
    private javax.swing.JFormattedTextField form_fecha;
    private javax.swing.JTextField form_precio;
    private javax.swing.JTable form_tablaProductos;
    private javax.swing.JLabel form_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
