package negocio.Forms;

import java.awt.Dimension;
import java.awt.Toolkit;

public class Principal extends javax.swing.JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        form_compras = new javax.swing.JButton();
        form_stocks = new javax.swing.JButton();
        form_abmProductos = new javax.swing.JButton();
        form_exit = new javax.swing.JButton();
        form_abmProveedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Programa de control de stock-compras");

        form_compras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form_compras.setText("Sector Compras");
        form_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_comprasActionPerformed(evt);
            }
        });

        form_stocks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form_stocks.setText("Sector Stocks");
        form_stocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_stocksActionPerformed(evt);
            }
        });

        form_abmProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form_abmProductos.setText("ABM Productos");
        form_abmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_abmProductosActionPerformed(evt);
            }
        });

        form_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form_exit.setText("Salir del programa");
        form_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_exitActionPerformed(evt);
            }
        });

        form_abmProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form_abmProveedores.setText("ABM Proveedores");
        form_abmProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_abmProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_stocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_abmProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_abmProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form_abmProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_abmProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_stocks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_compras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Constructor del form, aca declarar las variables y sus atributos.
    public Principal() {
        initComponents();
    }
    
    //Boton de salir del programa.
    private void form_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_form_exitActionPerformed

    //Boton para mostrar el ABM de los productos
    private void form_abmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_abmProductosActionPerformed
        ABMProductos productos = new ABMProductos(this, rootPaneCheckingEnabled);
        productos.setVisible(true);
    }//GEN-LAST:event_form_abmProductosActionPerformed

    //Boton para mostrar el ABM de los proveedores
    private void form_abmProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_abmProveedoresActionPerformed
        ABMProveedores proveedores = new ABMProveedores(this, rootPaneCheckingEnabled);
        proveedores.setVisible(true);
    }//GEN-LAST:event_form_abmProveedoresActionPerformed

    //Boton para mostrar la vista de los stocks de productos.
    private void form_stocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_stocksActionPerformed
        VistaStocks stocks = new VistaStocks(this, rootPaneCheckingEnabled);
        stocks.setVisible(true);
    }//GEN-LAST:event_form_stocksActionPerformed

    //Boton para mostrar la vista de las compras realizadas o realizar
    private void form_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_comprasActionPerformed
        VistaCompras compras = new VistaCompras(this, rootPaneCheckingEnabled);
        compras.setVisible(true);
    }//GEN-LAST:event_form_comprasActionPerformed

    //Main!!
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_abmProductos;
    private javax.swing.JButton form_abmProveedores;
    private javax.swing.JButton form_compras;
    private javax.swing.JButton form_exit;
    private javax.swing.JButton form_stocks;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
