/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio.Forms;

import java.awt.Frame;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import negocio.Controladoras.ControladoraCompras;
import negocio.Controladoras.ControladoraMedia;
import negocio.Controladoras.ControladoraProveedores;
import negocio.Controladoras.StorageException;
import negocio.Entidades.Compras;
import negocio.Entidades.Detalles;
import negocio.Entidades.Productos;
import negocio.Entidades.Proveedores;
import negocio.Hibernate.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author usuario
 */
public class VistaCompras extends javax.swing.JDialog {

    Frame framePrincipal = null;
    boolean alreadyShowed = false;
    /**
     * Creates new form VistaCompras
     */
    public VistaCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
        //Tener al Frame padre guardado para usar.
        framePrincipal = parent;
        //Seteo de los valores de las filas de la tabla en el centro
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i=0; i<form_tablaCompras.getColumnCount();i++){
            form_tablaCompras.setDefaultRenderer(form_tablaCompras.getColumnClass(i),renderer);
        }
        //Seteo de los valores de las cabezeras de la tabla en el centro
        DefaultTableCellRenderer renderer2 = (DefaultTableCellRenderer) form_tablaCompras.getTableHeader().getDefaultRenderer();
        renderer2.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_tablaCompras = new javax.swing.JTable();
        form_realizarNuevaCompra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        form_comboVerComprasProducto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        form_comboVerComprasProveedor = new javax.swing.JComboBox();
        form_modificarCompra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Sector para observar o realizar compras");

        form_tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Compra", "Fecha", "Proveedor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(form_tablaCompras);

        form_realizarNuevaCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_realizarNuevaCompra.setText("Realizar nueva compra");
        form_realizarNuevaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_realizarNuevaCompraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Ver compras de producto:");

        form_comboVerComprasProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Ver compras de proveedor:");

        form_comboVerComprasProveedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        form_modificarCompra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        form_modificarCompra.setText("Modificar seleccionada");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setText("Ver detalles de la seleccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_comboVerComprasProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(form_comboVerComprasProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(form_realizarNuevaCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(form_modificarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_comboVerComprasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(form_comboVerComprasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_realizarNuevaCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(form_modificarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento cuando la ventana gana foco, completar la tabla con compras, el combo de productos y el de proveedores.
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(!alreadyShowed){
            //Completar los combos de prod y prov.
            List<Proveedores> prov = null;
            List<Productos> prod = null;
            try {
                prov = ControladoraMedia.getProveedores();
                prod = ControladoraMedia.getProductos();
            } catch (StorageException ex) {
                Logger.getLogger(VistaCompras.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error al cargar los combos de productos y proveedores.","Error Vista Compras: formWindowGainedFocus!!",JOptionPane.WARNING_MESSAGE);
            }
            if(prov != null && prod != null)
                completarCombo(prov,prod);
            //Completar la tabla con todas las compras realizadas.
            List<Compras> listaCompras = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
                listaCompras = ControladoraCompras.getCompras(session);
            } catch (StorageException ex) {
                Logger.getLogger(VistaCompras.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error al cargar la lista de compras.","Error Vista Compras: formWindowGainedFocus!",JOptionPane.WARNING_MESSAGE);
            }
            if(listaCompras != null){
                //Agregar los valores a la tabla.
                for(Compras c : listaCompras){
                DefaultTableModel modelo = (DefaultTableModel) form_tablaCompras.getModel();
                String[] data = new String[5];
                data[0] = c.getIdCompra().toString();
                data[1] = c.getFecha().toString();
                Iterator it = c.getDetalleses().iterator();
                boolean foundName = false;
                int auxTotal = 0;
                while(it.hasNext()){
                    Detalles d = (Detalles) it.next();
                    //Obtener el nombre del proveedor de la compra.
                    if(!foundName){
                        int aux = d.getProductos().getIdProveedor();
                        try {
                            data[2] = ControladoraProveedores.getProveedor(aux).getProveedor();
                        } catch (StorageException ex) {
                            Logger.getLogger(VistaCompras.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null,"Error al intentar cargar el nombre del proveedor a la tabla.","Error Vista Compras: formWindowGainedFocus!",JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    //Obtener el total de la compra.
                    auxTotal += d.getTotal() * d.getCantidad();
                }
                data[3] = "$" + String.valueOf(auxTotal);
                modelo.addRow(data);
                form_tablaCompras.setModel(modelo);
                }
            }
            session.close();
            alreadyShowed = true;
        }
    }//GEN-LAST:event_formWindowGainedFocus

    //Funcion para completar los combobox con los valores de proveedores y productos.
    public void completarCombo(List<Proveedores> prov, List<Productos> prod){
        form_comboVerComprasProducto.addItem("Seleccionar...");
        form_comboVerComprasProveedor.addItem("Seleccionar...");
        for(Proveedores p : prov)
            form_comboVerComprasProveedor.addItem(p.getProveedor());
        for(Productos p : prod)
            form_comboVerComprasProducto.addItem(p.getProducto());
    }
    
    //Boton para mostrar el form de agregar compra
    private void form_realizarNuevaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_realizarNuevaCompraActionPerformed
        //Mostrar el nuevo formulario.
        AltaCompra compra = new AltaCompra(framePrincipal, rootPaneCheckingEnabled);
        compra.setVisible(true);
    }//GEN-LAST:event_form_realizarNuevaCompraActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaCompras dialog = new VistaCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox form_comboVerComprasProducto;
    private javax.swing.JComboBox form_comboVerComprasProveedor;
    private javax.swing.JButton form_modificarCompra;
    private javax.swing.JButton form_realizarNuevaCompra;
    private javax.swing.JTable form_tablaCompras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
