package negocio.Entidades;
// Generated 15/10/2014 10:44:15 by Hibernate Tools 4.3.1



/**
 * Detalles generated by hbm2java
 */
public class Detalles  implements java.io.Serializable {


     private DetallesId id;
     private Compras compras;
     private Productos productos;
     private Float total;
     private Integer cantidad;

    public Detalles() {
    }

	
    public Detalles(DetallesId id, Compras compras, Productos productos) {
        this.id = id;
        this.compras = compras;
        this.productos = productos;
    }
    public Detalles(DetallesId id, Compras compras, Productos productos, Float total, Integer cantidad) {
       this.id = id;
       this.compras = compras;
       this.productos = productos;
       this.total = total;
       this.cantidad = cantidad;
    }
   
    public DetallesId getId() {
        return this.id;
    }
    
    public void setId(DetallesId id) {
        this.id = id;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


