package negocio.Entidades;
// Generated 19/10/2014 12:45:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private String producto;
     private int stock;
     private Float precio;
     private int idProveedor;
     private Set detalleses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String producto, int stock, int idProveedor) {
        this.producto = producto;
        this.stock = stock;
        this.idProveedor = idProveedor;
    }
    public Productos(String producto, int stock, Float precio, int idProveedor, Set detalleses) {
       this.producto = producto;
       this.stock = stock;
       this.precio = precio;
       this.idProveedor = idProveedor;
       this.detalleses = detalleses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Set getDetalleses() {
        return this.detalleses;
    }
    
    public void setDetalleses(Set detalleses) {
        this.detalleses = detalleses;
    }




}


