package negocio.Entidades;
// Generated 15/10/2014 10:44:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Proveedores proveedores;
     private String producto;
     private int stock;
     private Float precio;
     private Set detalleses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Proveedores proveedores, String producto, int stock) {
        this.proveedores = proveedores;
        this.producto = producto;
        this.stock = stock;
    }
    public Productos(Proveedores proveedores, String producto, int stock, Float precio, Set detalleses) {
       this.proveedores = proveedores;
       this.producto = producto;
       this.stock = stock;
       this.precio = precio;
       this.detalleses = detalleses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getDetalleses() {
        return this.detalleses;
    }
    
    public void setDetalleses(Set detalleses) {
        this.detalleses = detalleses;
    }




}


