package negocio.Entidades;
// Generated 19/10/2014 12:45:40 by Hibernate Tools 4.3.1



/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idProveedor;
     private String proveedor;
     private String telefono;
     private String mail;

    public Proveedores() {
    }

    public Proveedores(String proveedor, String telefono, String mail) {
       this.proveedor = proveedor;
       this.telefono = telefono;
       this.mail = mail;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


